### ISSUE TITLE
Input/output Types

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#1366]
```[tasklist]
### Tasks
- [x] Identify the location of defining types in the PyExtractor
- [x] Identify the location of that will define types in the Rxtractor
- [ ] https://github.com/QCDIS/NaaVRE/issues/1381
- [ ] https://github.com/QCDIS/NaaVRE/issues/1382
- [ ] https://github.com/QCDIS/NaaVRE/issues/1383
```
