### ISSUE TITLE
Dynamic type detection

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#1432]
Implement a solution that relies on dynamic detection. 
We need to somehow connect to the kernel as it has been executed and look for the variables that are returned. 

We may add a button that will execute and analyze the cell.  

```[tasklist]
### Tasks
- [ ] https://github.com/QCDIS/NaaVRE/issues/1433
- [x] Inject code in the cell that gets the var type
- [x] Send the modified cell to the kernel for execution
- [ ] Retentive types and remove injected code
- [ ] https://github.com/QCDIS/NaaVRE/issues/1448
- [ ] https://github.com/QCDIS/NaaVRE/issues/1449
```
