### ISSUE TITLE
[Epic] Deploy alpha version for R kernel suport

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#667]
Deploy alpha version on the test cluster 
```[tasklist]
### Issues
- [ ] https://github.com/QCDIS/NaaVRE/issues/629
- [ ] https://github.com/QCDIS/NaaVRE/issues/668
- [ ] https://github.com/QCDIS/NaaVRE/issues/626
- [ ] https://github.com/QCDIS/NaaVRE/issues/630
```

**Comment by DiederikBlanson** [comment]
@skoulouzis this is done i think?
