### ISSUE TITLE
[Epic] Run R traits workflow

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#699]
# Description

Contebnarise and run an R use case from: https://github.com/QCDIS/lifewatch-notebooks/tree/main/demographic_and_morphological_traits 

```[tasklist]
# Issues
- [ ] https://github.com/QCDIS/infrastructure/issues/22
- [ ] https://github.com/QCDIS/NaaVRE/issues/696
- [ ] https://github.com/QCDIS/NaaVRE/issues/691
- [ ] https://github.com/QCDIS/NaaVRE/issues/689
- [ ] https://github.com/QCDIS/NaaVRE/issues/676
- [ ] https://github.com/QCDIS/NaaVRE/issues/675
- [ ] https://github.com/QCDIS/NaaVRE/issues/674
- [ ] https://github.com/QCDIS/NaaVRE/issues/672
- [ ] https://github.com/QCDIS/NaaVRE/issues/668
- [ ] https://github.com/QCDIS/NaaVRE/issues/694
- [ ] https://github.com/QCDIS/NaaVRE/issues/690
- [ ] https://github.com/QCDIS/NaaVRE/issues/688
- [ ] https://github.com/QCDIS/NaaVRE/issues/686
- [ ] https://github.com/QCDIS/NaaVRE/issues/685
- [ ] https://github.com/QCDIS/NaaVRE/issues/684
- [ ] https://github.com/QCDIS/NaaVRE/issues/683
- [ ] https://github.com/QCDIS/NaaVRE/issues/682
- [ ] https://github.com/QCDIS/NaaVRE/issues/681
```
